name: CI wheels and publish

on:
  push:
    branches: [main]
    tags:
      - "v*"
  pull_request:
    branches: [main]

jobs:
  build_wheels:
    name: Build wheels (${{ matrix.os }} / ${{ matrix.arch }} / ${{ matrix.python }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, macos-14]
        arch: [x86_64, aarch64, arm64]
        python: [cp310, cp311, cp312, cp313]
        exclude:
          - { os: ubuntu-latest, arch: arm64 }
          - { os: macos-13, arch: aarch64 }
          - { os: macos-13, arch: arm64 }
          - { os: macos-14, arch: aarch64 }
          - { os: macos-14, arch: x86_64 }

    steps:
      - uses: actions/checkout@v4

      - name: Derive ISLPY versions from tag or pyproject
        id: ver
        run: |
          ref="${GITHUB_REF:-${{ github.ref }}}"
          tag="${ref##*/}"
          if [[ "$tag" =~ ^v([0-9]+\.[0-9]+\.[0-9]+)(-[0-9]+)?$ ]]; then
            base_ver="${BASH_REMATCH[1]}"
            build_suffix="${BASH_REMATCH[2]}"
            full_ver="$base_ver${build_suffix}"
          else
            # Fallback to pyproject version without suffix
            base_ver=$(sed -n 's/^version\s*=\s*"\([^"]*\)"/\1/p' pyproject.toml | head -n1)
            full_ver="$base_ver"
          fi
          echo "ISLPY_VERSION=$full_ver" >> $GITHUB_ENV
          echo "ISLPY_BASE_VERSION=$base_ver" >> $GITHUB_ENV

      - name: Cache pip downloads
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Restore compiled prefix cache (GMP/NTL/Barvinok)
        id: restore-prefix
        uses: actions/cache/restore@v4
        with:
          path: ${{ github.workspace }}/build/prefix
          key: prefix-${{ matrix.os }}-${{ matrix.arch }}-gmp-6.3.0-ntl-10.5.0-barvinok-0.41.8
          restore-keys: |
            prefix-${{ matrix.os }}-${{ matrix.arch }}-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel

      - name: Enable QEMU for cross-architecture builds (Linux aarch64)
        if: runner.os == 'Linux' && matrix.arch == 'aarch64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Build wheels with cibuildwheel
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BUILD: ${{ matrix.python }}-*
          # We repair inside scripts/build_all.sh for both OSes; pass-through here
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: "bash -lc 'cp {wheel} {dest_dir}'"
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: "bash -lc 'cp {wheel} {dest_dir}'"
          BUILD_ROOT: ${{ github.workspace }}/build
          CIBW_ENVIRONMENT: ISLPY_VERSION=${{ env.ISLPY_VERSION }} ISLPY_BASE_VERSION=${{ env.ISLPY_BASE_VERSION }}
          CIBW_ENVIRONMENT_LINUX: BUILD_ROOT=/host${{ github.workspace }}/build/ ISLPY_VERSION=${{ env.ISLPY_VERSION }} ISLPY_BASE_VERSION=${{ env.ISLPY_BASE_VERSION }}
          ISLPY_VERSION: ${{ env.ISLPY_VERSION }}
          ISLPY_BASE_VERSION: ${{ env.ISLPY_BASE_VERSION }}
          # Install autotools in manylinux containers before building
          CIBW_BEFORE_ALL_LINUX: |
            yum install -y autoconf automake libtool pkgconfig git curl || \
            (dnf install -y autoconf automake libtool pkgconfig git curl || true)
          # Arch selection per platform
          CIBW_ARCHS_LINUX: ${{ matrix.os == 'ubuntu-latest' && matrix.arch || '' }}
          CIBW_MANYLINUX_AARCH64_IMAGE: quay.io/pypa/manylinux2014_aarch64
          CIBW_ARCHS_MACOS: ${{ startsWith(matrix.os, 'macos-') && matrix.arch || '' }}
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - name: Save compiled prefix cache (GMP/NTL/Barvinok)
        if: always()
        uses: actions/cache/save@v4
        with:
          path: ${{ github.workspace }}/build/prefix
          key: prefix-${{ matrix.os }}-${{ matrix.arch }}-gmp-6.3.0-ntl-10.5.0-barvinok-0.41.8

      - name: Upload wheel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.python }}
          path: wheelhouse/*.whl
          if-no-files-found: error

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Publish to PyPI
    needs: [build_wheels]
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for PyPI Trusted Publishing (OIDC)
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Derive ISLPY versions from tag
        run: |
          ref="${GITHUB_REF:-${{ github.ref }}}"
          tag="${ref##*/}"
          if [[ "$tag" =~ ^v([0-9]+\.[0-9]+\.[0-9]+)(-[0-9]+)?$ ]]; then
            base_ver="${BASH_REMATCH[1]}"
            build_suffix="${BASH_REMATCH[2]}"
            full_ver="$base_ver${build_suffix}"
          else
            echo "Unexpected tag format: $tag" >&2
            exit 1
          fi
          echo "ISLPY_VERSION=$full_ver" >> $GITHUB_ENV
          echo "ISLPY_BASE_VERSION=$base_ver" >> $GITHUB_ENV

      - name: Download wheel artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          merge-multiple: true
          path: dist-all

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build sdist
        run: |
          python -m pip install --upgrade pip build
          ISLPY_VERSION=${ISLPY_VERSION} python -m build --sdist
          mkdir -p dist-all
          cp dist/*.tar.gz dist-all/

      - name: List artifacts
        run: ls -l dist-all

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist-all
          skip-existing: true
